### ISSUE TITLE
Support Authorization

### ISSUE THREAD

**Issue by mdedetrich** [adyach/nakadi-docker#4]
Due to https://github.com/zalando-incubator/kanadi/issues/29 we need a way to test that the Authorization options for Kanadi client work.

The current Docker image is built without any auth options, we should build it with a dummy/mock auth provider that allows us to test features such as https://nakadi.io/manual.html#definition_EventTypeAuthorization

**Comment by adyach** [comment]
@mdedetrich than you for asking!
This repo is only about docker image, if you could provide the plugin, we can add to the image. I have filed a ticket in the Nakaid repo, once I have time I will implement it https://github.com/zalando/nakadi/issues/953

**Comment by adyach** [comment]
It was added. Instructions are here https://github.com/adyach/nakadi-docker#using-nakadi-project-provided-dependencies
