### ISSUE TITLE
arm64 -> amd64

### ISSUE THREAD

**Issue by ievgen-kapinos** [adyach/nakadi-docker#5]
Hi!

First of all. Thank you for publishing this image!

All previous versions except last one were for `amd64`. But the last one is for `arm64`.
See https://hub.docker.com/r/adyach/nakadi-docker/tags

May it was just a typo? Unfortunately the latest version does not work in my environment. 

Can you publish in Docker repository `amd64` version? 

P.S. Technically it is possible to have few images for different architectures under one version.

**Comment by adyach** [comment]
hi @ievgen-kapinos, it looks like I build it on arm64 machine. probably, I should build it using `buildx`. how urgent is that?

**Comment by ievgen-kapinos** [comment]
Hi @adyach I'm on previous version now. So it is not urgent, but nice to have whenever you have time

**Comment by puncleV** [comment]
Would be nice to have it updated as of with the same config it's working for Mac, but not for linux. So if you use in your `docker-compose` file latest\default version it will behave differently which is not nice.

**Comment by SergKam** [comment]
@adyach Long time no see! :) Would be nice to fix it, i spent 1 hour finding this issue. we are evaluating nakadi as an addition to aws managed Kafka we want to use in Zolar (btw what do you think is it possible?)

**Comment by adyach** [comment]
@SergKam hi 👋 :) I am a bit busy with Nakadi itself in the moment, but I will certainly fix it, I see it creates a lot of mess for people. 
it should not be a problem to integrate Nakadi with AWS MSK, however, there could be struggle in a place how Nakadi resolves brokers (it uses Zookeeper to do that) and I am not sure AWS MSK gives access to the Zookeeper.

**Comment by gchudnov** [comment]
@adyach 
Hi,
wondering, is it possible to fix this issue and create an image that can be run on linux?

at the moment the issue affects 2 PRs (https://github.com/zalando-nakadi/kanadi/pull/200 and https://github.com/zalando-nakadi/kanadi/pull/199) in kanadi-library.

Without tests it won't be possible to update Kanadi for avro, for example.

OR
Are there any other way to test is (e.g. a java mock-library that can be used instead)?

**Comment by roisin-jin** [comment]
Hi @adyach, just so you know we've also tried to use a previous version of the nakadi image in the PR but looks like docker has trouble of pulling it. We used `docker.pkg.github.com/adyach/nakadi-docker/nakadi:3.3.8` instead of version `latest`, is that the right hosting? If the previous version is working then we can use that one either. Many thanks

**Comment by adyach** [comment]
there is a new package for nakadi and postgres https://github.com/adyach/nakadi-docker/pkgs/container/nakadi-docker%2Fnakadi, which supports amd/arm. However, I had to change zookeeper and kafka images as well. feel free to test.

**Comment by gchudnov** [comment]
@adyach 
Thank you, will check!

**Comment by adyach** [comment]
@gchudnov I have also updated the example docker compose https://github.com/adyach/nakadi-docker/blob/master/docker-compose.yml

**Comment by ievgen-kapinos** [comment]
@adyach It works for our team who have ARM and AMD laptops. Thanks a lot. 

I'd to ask you also deprecate (mark somehow as deprecated) public docker repo
https://hub.docker.com/r/adyach/nakadi-docker/tags

It is very confusing and looks like alive source of latest images.

P.S. same `nakadi-postgres`

**Comment by ievgen-kapinos** [comment]
@adyach One more question

**Maybe can you suggest `nakadi-ui` Docker image for ARM/AMD?**

I've found only images in public Doker repo:
https://hub.docker.com/search?q=nakadi-ui

But these looks abandoned (last update was 2 years ago and more). All of them supports only AMD

**Comment by adyach** [comment]
@ievgen-kapinos that I can not suggest :(
